// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5WJHnUWP5OGZNaB76GG0dcL85dJoaIvM',
    appId: '1:787393223227:web:d5de6db0022f6944df9a1e',
    messagingSenderId: '787393223227',
    projectId: 'bragaresolve-f184d',
    authDomain: 'bragaresolve-f184d.firebaseapp.com',
    storageBucket: 'bragaresolve-f184d.firebasestorage.app',
    measurementId: 'G-RW4P6HSL2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeruiIPUcQP1eo4u2bKkDTproPi80_jFQ',
    appId: '1:787393223227:android:7870ec255830231fdf9a1e',
    messagingSenderId: '787393223227',
    projectId: 'bragaresolve-f184d',
    storageBucket: 'bragaresolve-f184d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6keFR9IDA8vuprTE_VfrDhmyoX0SbX7A',
    appId: '1:787393223227:ios:29708b6d26894a7fdf9a1e',
    messagingSenderId: '787393223227',
    projectId: 'bragaresolve-f184d',
    storageBucket: 'bragaresolve-f184d.firebasestorage.app',
    iosBundleId: 'com.example.bragaResolve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6keFR9IDA8vuprTE_VfrDhmyoX0SbX7A',
    appId: '1:787393223227:ios:29708b6d26894a7fdf9a1e',
    messagingSenderId: '787393223227',
    projectId: 'bragaresolve-f184d',
    storageBucket: 'bragaresolve-f184d.firebasestorage.app',
    iosBundleId: 'com.example.bragaResolve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5WJHnUWP5OGZNaB76GG0dcL85dJoaIvM',
    appId: '1:787393223227:web:38c96e25e97dff07df9a1e',
    messagingSenderId: '787393223227',
    projectId: 'bragaresolve-f184d',
    authDomain: 'bragaresolve-f184d.firebaseapp.com',
    storageBucket: 'bragaresolve-f184d.firebasestorage.app',
    measurementId: 'G-C0N2HPLN1T',
  );

}